apiVersion: v1
kind: Service
metadata:
  name: trade-backend
  namespace: trade
  labels:
    app: trade-backend
spec:
  selector:
    app: trade-backend
  ports:
  - port: 8000
    targetPort: 8000
    name: http
