apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-ingest
  namespace: trade
  labels:
    app: trade-ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-ingest
  template:
    metadata:
      labels:
        app: trade-ingest
    spec:
      nodeSelector:
        role: control
      containers:
      - name: ingest
        image: registry.local:5000/jdp/trade-ingest:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.data.svc:9092"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
