apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: default
data:
  config.yml: |
    tunnel: 05b88928-b53c-4ed6-aa52-6f1e0895f59d
    credentials-file: /etc/cloudflared/credentials.json

    ingress:
      - hostname: 6-6ho.com
        service: http://trade-frontend.trade.svc:80
      - hostname: www.6-6ho.com
        service: http://trade-frontend.trade.svc:80
      - hostname: trade.6-6ho.com
        service: http://trade-frontend.trade.svc:80
      - hostname: shop.6-6ho.com
        service: http://shop-analytics.shop.svc:80
      - hostname: admin.6-6ho.com
        service: http://shop-admin.shop.svc:80
      - hostname: analytics.6-6ho.com
        service: http://shop-analytics.shop.svc:80
      - hostname: airflow.6-6ho.com
        service: http://airflow-web.airflow.svc:8080
      - hostname: monitor.6-6ho.com
        service: http://grafana.monitoring.svc:3000
      - hostname: code.6-6ho.com
        service: http://ttyd.infra.svc:8080
      - service: http_status:404
