apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-monitor
  namespace: default
  labels:
    app: infra-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-monitor
  template:
    metadata:
      labels:
        app: infra-monitor
    spec:
      nodeSelector:
        role: control
      containers:
      - name: infra-monitor
        image: registry.local:5000/jdp/infra-monitor:latest
        envFrom:
        - secretRef:
            name: telegram-secret
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
