apiVersion: v1
kind: Service
metadata:
  name: shop-admin
  namespace: shop
  labels:
    app: shop-admin
spec:
  selector:
    app: shop-admin
  ports:
  - port: 80
    targetPort: 80
    name: http
