apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-admin
  namespace: shop
  labels:
    app: shop-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-admin
  template:
    metadata:
      labels:
        app: shop-admin
    spec:
      nodeSelector:
        role: worker
      containers:
      - name: admin
        image: registry.local:5000/jdp/shop-admin:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
