apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-analytics
  namespace: shop
  labels:
    app: shop-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-analytics
  template:
    metadata:
      labels:
        app: shop-analytics
    spec:
      nodeSelector:
        role: worker
      containers:
      - name: analytics
        image: registry.local:5000/jdp/shop-analytics:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
