apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: postgres:5432
    database: app
    user: postgres
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: "app"
      sslmode: "disable"
      postgresVersion: 1000  # 10.x+
    isDefault: false
    editable: true
