tunnel: 05b88928-b53c-4ed6-aa52-6f1e0895f59d
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: shop.6-6ho.com
    service: http://shop-api:3000
  - hostname: admin.6-6ho.com
    service: http://shop-admin:80
  - hostname: analytics.6-6ho.com
    service: http://shop-analytics:80
  - hostname: airflow.6-6ho.com
    service: http://airflow:8080
  - service: http_status:404
